# Generated by Django 2.2 on 2021-08-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='phase',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='manager.Project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
