# Generated by Django 2.2 on 2021-08-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210804_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='report',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.User')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.Task')),
            ],
        ),
    ]
