# Generated by Django 2.2 on 2021-08-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210814_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed',
        ),
    ]
