# Generated by Django 2.2 on 2021-08-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_project_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectManager', to='manager.User'),
        ),
    ]
